# Generated by Django 2.2 on 2020-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
                ('source', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
