# Generated by Django 2.2 on 2020-08-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
